# Site settings
title: My Life, My Dream 
header-img: img/home-bg.png
email: yonalin1@gmail.com
copyright_name: yanchanllin
description: > # this means to ignore newlines until "baseurl:"
  Live, Laugh
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  yanchanllin
learn_profile: yanchanllin
email_username: yonalin1@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
